version: "3.4"
services:
  aws:
    build: 
      dockerfile: ./Dockerfile
      context: ./
    entrypoint: bash
    working_dir: /${PROJECTE}
    volumes:
      - ./${LOCAL}:/${PROJECTE}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: eu-south-2
